import { CountryType } from "./country";
import { CountryCode, Currency } from "./enums";

export const countries: readonly CountryType[] = [
  {
    code: CountryCode.AL,
    label: "Albania",
    phone: "355",
    currency: Currency.ALL,
  },
  {
    code: CountryCode.AD,
    label: "Andorra",
    phone: "376",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.AM,
    label: "Armenia",
    phone: "374",
    currency: Currency.AMD,
  },
  {
    code: CountryCode.AT,
    label: "Austria",
    phone: "43",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.AZ,
    label: "Azerbaijan",
    phone: "994",
    currency: Currency.AZN,
  },
  {
    code: CountryCode.BA,
    label: "Bosnia and Herzegovina",
    phone: "387",
    currency: Currency.BAM,
  },
  {
    code: CountryCode.BE,
    label: "Belgium",
    phone: "32",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.BG,
    label: "Bulgaria",
    phone: "359",
    currency: Currency.BGN,
  },
  {
    code: CountryCode.HR,
    label: "Croatia",
    phone: "385",
    currency: Currency.HRK,
  },
  {
    code: CountryCode.CY,
    label: "Cyprus",
    phone: "357",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.CZ,
    label: "Czech Republic",
    phone: "420",
    currency: Currency.CZK,
  },
  {
    code: CountryCode.DK,
    label: "Denmark",
    phone: "45",
    currency: Currency.DKK,
  },
  {
    code: CountryCode.EE,
    label: "Estonia",
    phone: "372",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.FO,
    label: "Faroe Islands",
    phone: "298",
    currency: Currency.DKK,
  },
  {
    code: CountryCode.FI,
    label: "Finland",
    phone: "358",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.FR,
    label: "France",
    phone: "33",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.GE,
    label: "Georgia",
    phone: "995",
    currency: Currency.GEL,
  },
  {
    code: CountryCode.DE,
    label: "Germany",
    phone: "49",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.GR,
    label: "Greece",
    phone: "30",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.GL,
    label: "Greenland",
    phone: "299",
    currency: Currency.DKK,
  },
  {
    code: CountryCode.HU,
    label: "Hungary",
    phone: "36",
    currency: Currency.HUF,
  },
  {
    code: CountryCode.IS,
    label: "Iceland",
    phone: "354",
    currency: Currency.ISK,
  },
  {
    code: CountryCode.IE,
    label: "Ireland",
    phone: "353",
    currency: Currency.EUR,
  },
  { code: CountryCode.IT, label: "Italy", phone: "39", currency: Currency.EUR },
  {
    code: CountryCode.KZ,
    label: "Kazakhstan",
    phone: "7",
    currency: Currency.KZT,
  },
  {
    code: CountryCode.XK,
    label: "Kosovo",
    phone: "383",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.LI,
    label: "Liechtenstein",
    phone: "423",
    currency: Currency.CHF,
  },
  {
    code: CountryCode.LT,
    label: "Lithuania",
    phone: "370",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.LU,
    label: "Luxembourg",
    phone: "352",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.LV,
    label: "Latvia",
    phone: "371",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.MC,
    label: "Monaco",
    phone: "377",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.MD,
    label: "Moldova",
    phone: "373",
    currency: Currency.MDL,
  },
  {
    code: CountryCode.ME,
    label: "Montenegro",
    phone: "382",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.MK,
    label: "Macedonia",
    phone: "389",
    currency: Currency.MKD,
  },
  {
    code: CountryCode.MT,
    label: "Malta",
    phone: "356",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.NL,
    label: "Netherlands",
    phone: "31",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.NO,
    label: "Norway",
    phone: "47",
    currency: Currency.NOK,
  },
  {
    code: CountryCode.PL,
    label: "Poland",
    phone: "48",
    currency: Currency.PLN,
  },
  {
    code: CountryCode.PT,
    label: "Portugal",
    phone: "351",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.RO,
    label: "Romania",
    phone: "40",
    currency: Currency.RON,
  },
  {
    code: CountryCode.RS,
    label: "Serbia",
    phone: "381",
    currency: Currency.RSD,
  },
  {
    code: CountryCode.SE,
    label: "Sweden",
    phone: "46",
    currency: Currency.SEK,
  },
  {
    code: CountryCode.SI,
    label: "Slovenia",
    phone: "386",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.SK,
    label: "Slovakia",
    phone: "421",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.SM,
    label: "San Marino",
    phone: "378",
    currency: Currency.EUR,
  },
  {
    code: CountryCode.UA,
    label: "Ukraine",
    phone: "380",
    currency: Currency.UAH,
  },
  {
    code: CountryCode.GB,
    label: "United Kingdom",
    phone: "44",
    currency: Currency.GBP,
  },
  {
    code: CountryCode.VA,
    label: "Vatican City",
    phone: "379",
    currency: Currency.EUR,
  },
];
